linestorm_cms_admin_module_comment_list:
    pattern:  /
    defaults: { _controller: LineStormCommentBundle:Admin:list }

linestorm_cms_admin_module_comment_view:
    pattern:  /{id}
    defaults: { _controller: LineStormCommentBundle:Admin:view }
    requirements:
       id: \d+

linestorm_cms_admin_module_comment_edit:
    pattern:  /{id}/edit
    defaults: { _controller: LineStormCommentBundle:Admin:edit }
    requirements:
       id: \d+

