linestorm_comment_api_provider_controller:
    type:         rest
    resource:     LineStorm\CommentBundle\Controller\ProviderController
    name_prefix:  linestorm_comment_api_

linestorm_comment_api_threads_controller:
    type:         rest
    parent:       linestorm_comment_api_provider_controller
    resource:     LineStorm\CommentBundle\Controller\ThreadController
    name_prefix:  linestorm_comment_api_

linestorm_comment_api_comments_controller:
    type:         rest
    parent:       linestorm_comment_api_threads_controller
    resource:     LineStorm\CommentBundle\Controller\CommentController
    name_prefix:  linestorm_comment_api_
